version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crud-api-generator
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php-fpm.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - crud-api-network

  nginx:
    image: nginx:alpine
    container_name: crud-api-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - crud-api-network

  db:
    image: mysql:8.0
    container_name: crud-api-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - crud-api-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crud-api-phpmyadmin
    restart: unless-stopped
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - crud-api-network

networks:
  crud-api-network:
    driver: bridge 